version: "3"

services:
  janusgraph:
    image: experoinc/janusgraph:0.2.0
    container_name: jce-janusgraph
    environment:
      JANUS_STORAGE_BACKEND: cql
      JANUS_STORAGE_HOSTNAME: jce-cassandra
      JANUS_INDEXES: search
      JANUS_INDEX_HOSTNAME: jce-elastic
      JANUS_GREMLIN_CHANNELIZER: org.apache.tinkerpop.gremlin.server.channel.HttpChannelizer
    ports:
      - "8182:8182"
    networks:
      - jce-network
    healthcheck:
    #curl -X POST -Hcontent-type:application/json -d '{"gremlin" : "g.V().count()"}' http://localhost:8182
      test: ["CMD", "curl", "-X", "POST", "-Hcontent-type:application/json", "-f", "-d", "{\"gremlin\" : \"g.V(1).hasNext()\" }", "http://localhost:8182"]
      interval: 30s
      timeout: 5s
      retries: 1
  cassandra:
    image: cassandra:3
    container_name: jce-cassandra
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      CASSANDRA_START_RPC: 'true'
    networks:
      - jce-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: jce-elastic
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "cluster.name=docker-cluster"
      - "xpack.security.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
    ports:
      - "9200:9200"
    networks:
      - jce-network

networks:
  jce-network:
volumes:
  janusgraph-default-data:
